<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title>-</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="css/main.css" type="text/css" media="screen,projection" />

</head>
 
<body>

<div id="wrapper">

		<div id="header">
		
				<p class="description">
				
						An imageless template focusing on Typography.
				
				</p>
				
				<h1><a href="#">Typography Paramount</a></h1>
				
				<ul id="nav">
				
						<li><a href="#">Link Here</a></li>
						
						<li><a href="#" class="active">Link Here</a></li>
						
						<li><a href="#">Link Here</a></li>
						
						<li><a href="#">Link Here</a></li>
						
						<li><a href="#">Link Here</a></li>
				
						
				
				</ul>
		
		</div>
		
		<div id="sidebar">
		
				<h2>Latest News</h2>
				
				<p class="news">
					An example of a "latest news" type text area. Here would be the excerpt of the article. You can of course put anything you like here.
					<a href="#" class="more">Read More &raquo;</a>
				</p>
				
				<p class="news">
					An example of a "latest news" type text area. Here would be the excerpt of the article. You can of course put anything you like here.
					<a href="#" class="more">Read More &raquo;</a>
				</p>
				
				<p class="news">
					An example of a "latest news" type text area. Here would be the excerpt of the article. You can of course put anything you like here.
					<a href="#" class="more">Read More &raquo;</a>
				</p>
				
				<h2>Sub Navigation</h2>
				
				<ul>
				
						<li><a href="#">Link Here</a></li>
						
						<li><a href="#">Link Here</a></li>
						
						<li><a href="#">Link Here</a></li>
						
						<li><a href="#">Link Here</a></li>
				
				</ul>
				
				<h2>Search</h2>
				
				<input name="" type="text" />
		
		</div>
		
		<div id="content">